apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu10-java-petstore
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu10-java-petstore
spec:
  source:
    git:
      url: https://github.com/Azure-Samples/Java-application-petstore-ee7.git
      ref:
        branch: master