apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu10-java-native
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu10-java-native
spec:
  build:
    env:
    - name: BP_NATIVE_IMAGE
      value: "true"
  source:
    git:
      url: https://github.com/showpune/tanzu10-java-web-app.git
      ref:
        branch: master